In [1]:
import pandas as pd
df = pd.read_csv('insurance.csv')

In [2]:
df.head

<bound method NDFrame.head of       age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]>

In [ ]:
df = df.drop

In [8]:
dtype = df.dtypes
nunique = df.nunique()
pd.DataFrame({'dtype': dtype, 'nunique': nunique}).T

           age  sex      bmi children smoker region  charges
dtype    int64  str  float64    int64    str    str  float64
nunique     47    2      548        6      2      4     1337

In [9]:
cols = ["sex", "children", "smoker", "region"]
df[cols] = df[cols].astype("category")

pd.DataFrame({"dtype": df.dtypes, "nunique": df.nunique()}).T

           age       sex      bmi  children    smoker    region  charges
dtype    int64  category  float64  category  category  category  float64
nunique     47         2      548         6         2         4     1337

In [14]:
null = df.isnull().sum()
ratio = null / len(df)
pd.DataFrame({"null": null, "ratio": ratio}).T

       age  sex  bmi  children  smoker  region  charges
null   0.0  0.0  0.0       0.0     0.0     0.0      0.0
ratio  0.0  0.0  0.0       0.0     0.0     0.0      0.0

In [15]:
df.describe()

               age          bmi       charges
count  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397  13270.422265
std      14.049960     6.098187  12110.011237
min      18.000000    15.960000   1121.873900
25%      27.000000    26.296250   4740.287150
50%      39.000000    30.400000   9382.033000
75%      51.000000    34.693750  16639.912515
max      64.000000    53.130000  63770.428010